// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/packets/PlayerPacket.proto

public final class PlayerPacketProto {
  private PlayerPacketProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code UpdateType}
   */
  public enum UpdateType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>IDLE = 0;</code>
     */
    IDLE(0),
    /**
     * <code>MOVED = 1;</code>
     */
    MOVED(1),
    /**
     * <code>RUNNING = 2;</code>
     */
    RUNNING(2),
    /**
     * <code>TELEPORT = 3;</code>
     */
    TELEPORT(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>IDLE = 0;</code>
     */
    public static final int IDLE_VALUE = 0;
    /**
     * <code>MOVED = 1;</code>
     */
    public static final int MOVED_VALUE = 1;
    /**
     * <code>RUNNING = 2;</code>
     */
    public static final int RUNNING_VALUE = 2;
    /**
     * <code>TELEPORT = 3;</code>
     */
    public static final int TELEPORT_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static UpdateType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static UpdateType forNumber(int value) {
      switch (value) {
        case 0: return IDLE;
        case 1: return MOVED;
        case 2: return RUNNING;
        case 3: return TELEPORT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<UpdateType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        UpdateType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<UpdateType>() {
            public UpdateType findValueByNumber(int number) {
              return UpdateType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return PlayerPacketProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final UpdateType[] VALUES = values();

    public static UpdateType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private UpdateType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:UpdateType)
  }

  public interface PlayerPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:PlayerPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool IsUpdating = 1;</code>
     * @return The isUpdating.
     */
    boolean getIsUpdating();

    /**
     * <code>.UpdateType Type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    int getTypeValue();
    /**
     * <code>.UpdateType Type = 2;</code>
     * @return The type.
     */
    PlayerPacketProto.UpdateType getType();

    /**
     * <code>uint32 NewDirection = 3;</code>
     * @return The newDirection.
     */
    int getNewDirection();

    /**
     * <code>uint32 OldDirection = 4;</code>
     * @return The oldDirection.
     */
    int getOldDirection();

    /**
     * <code>uint32 Height = 5;</code>
     * @return The height.
     */
    int getHeight();

    /**
     * <code>bool ClearFlag = 6;</code>
     * @return The clearFlag.
     */
    boolean getClearFlag();

    /**
     * <code>bool UpdateRequired = 7;</code>
     * @return The updateRequired.
     */
    boolean getUpdateRequired();

    /**
     * <code>uint32 X = 8;</code>
     * @return The x.
     */
    int getX();

    /**
     * <code>uint32 Y = 9;</code>
     * @return The y.
     */
    int getY();
  }
  /**
   * Protobuf type {@code PlayerPacket}
   */
  public  static final class PlayerPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:PlayerPacket)
      PlayerPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerPacket.newBuilder() to construct.
    private PlayerPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerPacket() {
      type_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerPacket();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              isUpdating_ = input.readBool();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 24: {

              newDirection_ = input.readUInt32();
              break;
            }
            case 32: {

              oldDirection_ = input.readUInt32();
              break;
            }
            case 40: {

              height_ = input.readUInt32();
              break;
            }
            case 48: {

              clearFlag_ = input.readBool();
              break;
            }
            case 56: {

              updateRequired_ = input.readBool();
              break;
            }
            case 64: {

              x_ = input.readUInt32();
              break;
            }
            case 72: {

              y_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PlayerPacketProto.internal_static_PlayerPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PlayerPacketProto.internal_static_PlayerPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PlayerPacketProto.PlayerPacket.class, PlayerPacketProto.PlayerPacket.Builder.class);
    }

    public static final int ISUPDATING_FIELD_NUMBER = 1;
    private boolean isUpdating_;
    /**
     * <code>bool IsUpdating = 1;</code>
     * @return The isUpdating.
     */
    public boolean getIsUpdating() {
      return isUpdating_;
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private int type_;
    /**
     * <code>.UpdateType Type = 2;</code>
     * @return The enum numeric value on the wire for type.
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.UpdateType Type = 2;</code>
     * @return The type.
     */
    public PlayerPacketProto.UpdateType getType() {
      @SuppressWarnings("deprecation")
      PlayerPacketProto.UpdateType result = PlayerPacketProto.UpdateType.valueOf(type_);
      return result == null ? PlayerPacketProto.UpdateType.UNRECOGNIZED : result;
    }

    public static final int NEWDIRECTION_FIELD_NUMBER = 3;
    private int newDirection_;
    /**
     * <code>uint32 NewDirection = 3;</code>
     * @return The newDirection.
     */
    public int getNewDirection() {
      return newDirection_;
    }

    public static final int OLDDIRECTION_FIELD_NUMBER = 4;
    private int oldDirection_;
    /**
     * <code>uint32 OldDirection = 4;</code>
     * @return The oldDirection.
     */
    public int getOldDirection() {
      return oldDirection_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 5;
    private int height_;
    /**
     * <code>uint32 Height = 5;</code>
     * @return The height.
     */
    public int getHeight() {
      return height_;
    }

    public static final int CLEARFLAG_FIELD_NUMBER = 6;
    private boolean clearFlag_;
    /**
     * <code>bool ClearFlag = 6;</code>
     * @return The clearFlag.
     */
    public boolean getClearFlag() {
      return clearFlag_;
    }

    public static final int UPDATEREQUIRED_FIELD_NUMBER = 7;
    private boolean updateRequired_;
    /**
     * <code>bool UpdateRequired = 7;</code>
     * @return The updateRequired.
     */
    public boolean getUpdateRequired() {
      return updateRequired_;
    }

    public static final int X_FIELD_NUMBER = 8;
    private int x_;
    /**
     * <code>uint32 X = 8;</code>
     * @return The x.
     */
    public int getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 9;
    private int y_;
    /**
     * <code>uint32 Y = 9;</code>
     * @return The y.
     */
    public int getY() {
      return y_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (isUpdating_ != false) {
        output.writeBool(1, isUpdating_);
      }
      if (type_ != PlayerPacketProto.UpdateType.IDLE.getNumber()) {
        output.writeEnum(2, type_);
      }
      if (newDirection_ != 0) {
        output.writeUInt32(3, newDirection_);
      }
      if (oldDirection_ != 0) {
        output.writeUInt32(4, oldDirection_);
      }
      if (height_ != 0) {
        output.writeUInt32(5, height_);
      }
      if (clearFlag_ != false) {
        output.writeBool(6, clearFlag_);
      }
      if (updateRequired_ != false) {
        output.writeBool(7, updateRequired_);
      }
      if (x_ != 0) {
        output.writeUInt32(8, x_);
      }
      if (y_ != 0) {
        output.writeUInt32(9, y_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (isUpdating_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isUpdating_);
      }
      if (type_ != PlayerPacketProto.UpdateType.IDLE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, type_);
      }
      if (newDirection_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, newDirection_);
      }
      if (oldDirection_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, oldDirection_);
      }
      if (height_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, height_);
      }
      if (clearFlag_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(6, clearFlag_);
      }
      if (updateRequired_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, updateRequired_);
      }
      if (x_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, x_);
      }
      if (y_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, y_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PlayerPacketProto.PlayerPacket)) {
        return super.equals(obj);
      }
      PlayerPacketProto.PlayerPacket other = (PlayerPacketProto.PlayerPacket) obj;

      if (getIsUpdating()
          != other.getIsUpdating()) return false;
      if (type_ != other.type_) return false;
      if (getNewDirection()
          != other.getNewDirection()) return false;
      if (getOldDirection()
          != other.getOldDirection()) return false;
      if (getHeight()
          != other.getHeight()) return false;
      if (getClearFlag()
          != other.getClearFlag()) return false;
      if (getUpdateRequired()
          != other.getUpdateRequired()) return false;
      if (getX()
          != other.getX()) return false;
      if (getY()
          != other.getY()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ISUPDATING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsUpdating());
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + NEWDIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + getNewDirection();
      hash = (37 * hash) + OLDDIRECTION_FIELD_NUMBER;
      hash = (53 * hash) + getOldDirection();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getHeight();
      hash = (37 * hash) + CLEARFLAG_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getClearFlag());
      hash = (37 * hash) + UPDATEREQUIRED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getUpdateRequired());
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + getX();
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + getY();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PlayerPacketProto.PlayerPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlayerPacketProto.PlayerPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlayerPacketProto.PlayerPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlayerPacketProto.PlayerPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlayerPacketProto.PlayerPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PlayerPacketProto.PlayerPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PlayerPacketProto.PlayerPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlayerPacketProto.PlayerPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlayerPacketProto.PlayerPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static PlayerPacketProto.PlayerPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PlayerPacketProto.PlayerPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static PlayerPacketProto.PlayerPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PlayerPacketProto.PlayerPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code PlayerPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:PlayerPacket)
        PlayerPacketProto.PlayerPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PlayerPacketProto.internal_static_PlayerPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PlayerPacketProto.internal_static_PlayerPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PlayerPacketProto.PlayerPacket.class, PlayerPacketProto.PlayerPacket.Builder.class);
      }

      // Construct using PlayerPacketProto.PlayerPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        isUpdating_ = false;

        type_ = 0;

        newDirection_ = 0;

        oldDirection_ = 0;

        height_ = 0;

        clearFlag_ = false;

        updateRequired_ = false;

        x_ = 0;

        y_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PlayerPacketProto.internal_static_PlayerPacket_descriptor;
      }

      @java.lang.Override
      public PlayerPacketProto.PlayerPacket getDefaultInstanceForType() {
        return PlayerPacketProto.PlayerPacket.getDefaultInstance();
      }

      @java.lang.Override
      public PlayerPacketProto.PlayerPacket build() {
        PlayerPacketProto.PlayerPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PlayerPacketProto.PlayerPacket buildPartial() {
        PlayerPacketProto.PlayerPacket result = new PlayerPacketProto.PlayerPacket(this);
        result.isUpdating_ = isUpdating_;
        result.type_ = type_;
        result.newDirection_ = newDirection_;
        result.oldDirection_ = oldDirection_;
        result.height_ = height_;
        result.clearFlag_ = clearFlag_;
        result.updateRequired_ = updateRequired_;
        result.x_ = x_;
        result.y_ = y_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PlayerPacketProto.PlayerPacket) {
          return mergeFrom((PlayerPacketProto.PlayerPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PlayerPacketProto.PlayerPacket other) {
        if (other == PlayerPacketProto.PlayerPacket.getDefaultInstance()) return this;
        if (other.getIsUpdating() != false) {
          setIsUpdating(other.getIsUpdating());
        }
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getNewDirection() != 0) {
          setNewDirection(other.getNewDirection());
        }
        if (other.getOldDirection() != 0) {
          setOldDirection(other.getOldDirection());
        }
        if (other.getHeight() != 0) {
          setHeight(other.getHeight());
        }
        if (other.getClearFlag() != false) {
          setClearFlag(other.getClearFlag());
        }
        if (other.getUpdateRequired() != false) {
          setUpdateRequired(other.getUpdateRequired());
        }
        if (other.getX() != 0) {
          setX(other.getX());
        }
        if (other.getY() != 0) {
          setY(other.getY());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        PlayerPacketProto.PlayerPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (PlayerPacketProto.PlayerPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean isUpdating_ ;
      /**
       * <code>bool IsUpdating = 1;</code>
       * @return The isUpdating.
       */
      public boolean getIsUpdating() {
        return isUpdating_;
      }
      /**
       * <code>bool IsUpdating = 1;</code>
       * @param value The isUpdating to set.
       * @return This builder for chaining.
       */
      public Builder setIsUpdating(boolean value) {
        
        isUpdating_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool IsUpdating = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsUpdating() {
        
        isUpdating_ = false;
        onChanged();
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.UpdateType Type = 2;</code>
       * @return The enum numeric value on the wire for type.
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.UpdateType Type = 2;</code>
       * @param value The enum numeric value on the wire for type to set.
       * @return This builder for chaining.
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.UpdateType Type = 2;</code>
       * @return The type.
       */
      public PlayerPacketProto.UpdateType getType() {
        @SuppressWarnings("deprecation")
        PlayerPacketProto.UpdateType result = PlayerPacketProto.UpdateType.valueOf(type_);
        return result == null ? PlayerPacketProto.UpdateType.UNRECOGNIZED : result;
      }
      /**
       * <code>.UpdateType Type = 2;</code>
       * @param value The type to set.
       * @return This builder for chaining.
       */
      public Builder setType(PlayerPacketProto.UpdateType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.UpdateType Type = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private int newDirection_ ;
      /**
       * <code>uint32 NewDirection = 3;</code>
       * @return The newDirection.
       */
      public int getNewDirection() {
        return newDirection_;
      }
      /**
       * <code>uint32 NewDirection = 3;</code>
       * @param value The newDirection to set.
       * @return This builder for chaining.
       */
      public Builder setNewDirection(int value) {
        
        newDirection_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 NewDirection = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNewDirection() {
        
        newDirection_ = 0;
        onChanged();
        return this;
      }

      private int oldDirection_ ;
      /**
       * <code>uint32 OldDirection = 4;</code>
       * @return The oldDirection.
       */
      public int getOldDirection() {
        return oldDirection_;
      }
      /**
       * <code>uint32 OldDirection = 4;</code>
       * @param value The oldDirection to set.
       * @return This builder for chaining.
       */
      public Builder setOldDirection(int value) {
        
        oldDirection_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 OldDirection = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearOldDirection() {
        
        oldDirection_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>uint32 Height = 5;</code>
       * @return The height.
       */
      public int getHeight() {
        return height_;
      }
      /**
       * <code>uint32 Height = 5;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(int value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 Height = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        
        height_ = 0;
        onChanged();
        return this;
      }

      private boolean clearFlag_ ;
      /**
       * <code>bool ClearFlag = 6;</code>
       * @return The clearFlag.
       */
      public boolean getClearFlag() {
        return clearFlag_;
      }
      /**
       * <code>bool ClearFlag = 6;</code>
       * @param value The clearFlag to set.
       * @return This builder for chaining.
       */
      public Builder setClearFlag(boolean value) {
        
        clearFlag_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool ClearFlag = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearClearFlag() {
        
        clearFlag_ = false;
        onChanged();
        return this;
      }

      private boolean updateRequired_ ;
      /**
       * <code>bool UpdateRequired = 7;</code>
       * @return The updateRequired.
       */
      public boolean getUpdateRequired() {
        return updateRequired_;
      }
      /**
       * <code>bool UpdateRequired = 7;</code>
       * @param value The updateRequired to set.
       * @return This builder for chaining.
       */
      public Builder setUpdateRequired(boolean value) {
        
        updateRequired_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool UpdateRequired = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearUpdateRequired() {
        
        updateRequired_ = false;
        onChanged();
        return this;
      }

      private int x_ ;
      /**
       * <code>uint32 X = 8;</code>
       * @return The x.
       */
      public int getX() {
        return x_;
      }
      /**
       * <code>uint32 X = 8;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(int value) {
        
        x_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 X = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        
        x_ = 0;
        onChanged();
        return this;
      }

      private int y_ ;
      /**
       * <code>uint32 Y = 9;</code>
       * @return The y.
       */
      public int getY() {
        return y_;
      }
      /**
       * <code>uint32 Y = 9;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(int value) {
        
        y_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 Y = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        
        y_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:PlayerPacket)
    }

    // @@protoc_insertion_point(class_scope:PlayerPacket)
    private static final PlayerPacketProto.PlayerPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PlayerPacketProto.PlayerPacket();
    }

    public static PlayerPacketProto.PlayerPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PlayerPacket>
        PARSER = new com.google.protobuf.AbstractParser<PlayerPacket>() {
      @java.lang.Override
      public PlayerPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PlayerPacketProto.PlayerPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_PlayerPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_PlayerPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(src/main/java/packets/PlayerPacket.pro" +
      "to\"\272\001\n\014PlayerPacket\022\022\n\nIsUpdating\030\001 \001(\010\022" +
      "\031\n\004Type\030\002 \001(\0162\013.UpdateType\022\024\n\014NewDirecti" +
      "on\030\003 \001(\r\022\024\n\014OldDirection\030\004 \001(\r\022\016\n\006Height" +
      "\030\005 \001(\r\022\021\n\tClearFlag\030\006 \001(\010\022\026\n\016UpdateRequi" +
      "red\030\007 \001(\010\022\t\n\001X\030\010 \001(\r\022\t\n\001Y\030\t \001(\r*<\n\nUpdat" +
      "eType\022\010\n\004IDLE\020\000\022\t\n\005MOVED\020\001\022\013\n\007RUNNING\020\002\022" +
      "\014\n\010TELEPORT\020\003B\023B\021PlayerPacketProtob\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_PlayerPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_PlayerPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_PlayerPacket_descriptor,
        new java.lang.String[] { "IsUpdating", "Type", "NewDirection", "OldDirection", "Height", "ClearFlag", "UpdateRequired", "X", "Y", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
