// Code generated by protoc-gen-go. DO NOT EDIT.
// source: src/main/java/packets/PlayerPacket.proto

package packet

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateType int32

const (
	UpdateType_IDLE     UpdateType = 0
	UpdateType_MOVED    UpdateType = 1
	UpdateType_RUNNING  UpdateType = 2
	UpdateType_TELEPORT UpdateType = 3
)

var UpdateType_name = map[int32]string{
	0: "IDLE",
	1: "MOVED",
	2: "RUNNING",
	3: "TELEPORT",
}

var UpdateType_value = map[string]int32{
	"IDLE":     0,
	"MOVED":    1,
	"RUNNING":  2,
	"TELEPORT": 3,
}

func (x UpdateType) String() string {
	return proto.EnumName(UpdateType_name, int32(x))
}

func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_072eba0ea152a2ef, []int{0}
}

type PlayerPacket struct {
	IsUpdating           bool       `protobuf:"varint,1,opt,name=IsUpdating,proto3" json:"IsUpdating,omitempty"`
	Type                 UpdateType `protobuf:"varint,2,opt,name=Type,proto3,enum=UpdateType" json:"Type,omitempty"`
	NewDirection         uint32     `protobuf:"varint,3,opt,name=NewDirection,proto3" json:"NewDirection,omitempty"`
	OldDirection         uint32     `protobuf:"varint,4,opt,name=OldDirection,proto3" json:"OldDirection,omitempty"`
	Height               uint32     `protobuf:"varint,5,opt,name=Height,proto3" json:"Height,omitempty"`
	ClearFlag            bool       `protobuf:"varint,6,opt,name=ClearFlag,proto3" json:"ClearFlag,omitempty"`
	UpdateRequired       bool       `protobuf:"varint,7,opt,name=UpdateRequired,proto3" json:"UpdateRequired,omitempty"`
	X                    uint32     `protobuf:"varint,8,opt,name=X,proto3" json:"X,omitempty"`
	Y                    uint32     `protobuf:"varint,9,opt,name=Y,proto3" json:"Y,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PlayerPacket) Reset()         { *m = PlayerPacket{} }
func (m *PlayerPacket) String() string { return proto.CompactTextString(m) }
func (*PlayerPacket) ProtoMessage()    {}
func (*PlayerPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_072eba0ea152a2ef, []int{0}
}

func (m *PlayerPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerPacket.Unmarshal(m, b)
}
func (m *PlayerPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerPacket.Marshal(b, m, deterministic)
}
func (m *PlayerPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerPacket.Merge(m, src)
}
func (m *PlayerPacket) XXX_Size() int {
	return xxx_messageInfo_PlayerPacket.Size(m)
}
func (m *PlayerPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerPacket.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerPacket proto.InternalMessageInfo

func (m *PlayerPacket) GetIsUpdating() bool {
	if m != nil {
		return m.IsUpdating
	}
	return false
}

func (m *PlayerPacket) GetType() UpdateType {
	if m != nil {
		return m.Type
	}
	return UpdateType_IDLE
}

func (m *PlayerPacket) GetNewDirection() uint32 {
	if m != nil {
		return m.NewDirection
	}
	return 0
}

func (m *PlayerPacket) GetOldDirection() uint32 {
	if m != nil {
		return m.OldDirection
	}
	return 0
}

func (m *PlayerPacket) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *PlayerPacket) GetClearFlag() bool {
	if m != nil {
		return m.ClearFlag
	}
	return false
}

func (m *PlayerPacket) GetUpdateRequired() bool {
	if m != nil {
		return m.UpdateRequired
	}
	return false
}

func (m *PlayerPacket) GetX() uint32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *PlayerPacket) GetY() uint32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterEnum("UpdateType", UpdateType_name, UpdateType_value)
	proto.RegisterType((*PlayerPacket)(nil), "PlayerPacket")
}

func init() {
	proto.RegisterFile("src/main/java/packets/PlayerPacket.proto", fileDescriptor_072eba0ea152a2ef)
}

var fileDescriptor_072eba0ea152a2ef = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcd, 0x4e, 0xb3, 0x40,
	0x18, 0x85, 0xbf, 0xe9, 0x2f, 0x7d, 0xcb, 0xd7, 0xe0, 0x98, 0x98, 0x59, 0x18, 0x6d, 0xba, 0x30,
	0xc4, 0x45, 0x49, 0x74, 0xeb, 0xaa, 0x82, 0x4a, 0x52, 0x81, 0x4c, 0xa8, 0x69, 0x97, 0x23, 0x4c,
	0x70, 0x14, 0x01, 0x07, 0xd4, 0xf4, 0x32, 0xbc, 0x63, 0xc3, 0x60, 0x02, 0xba, 0x3c, 0xcf, 0x79,
	0x32, 0x79, 0xe7, 0x80, 0x59, 0xca, 0xc8, 0x7a, 0x65, 0x22, 0xb3, 0x9e, 0xd9, 0x07, 0xb3, 0x0a,
	0x16, 0xbd, 0xf0, 0xaa, 0xb4, 0x82, 0x94, 0xed, 0xb9, 0x0c, 0x54, 0x5a, 0x16, 0x32, 0xaf, 0xf2,
	0xc5, 0x57, 0x0f, 0xf4, 0x2e, 0xc6, 0x27, 0x00, 0x6e, 0xb9, 0x29, 0x62, 0x56, 0x89, 0x2c, 0x21,
	0x68, 0x8e, 0x4c, 0x8d, 0x76, 0x08, 0x3e, 0x85, 0x41, 0xb8, 0x2f, 0x38, 0xe9, 0xcd, 0x91, 0x39,
	0xbb, 0x98, 0x2e, 0x55, 0xc1, 0x6b, 0x44, 0x55, 0x81, 0x17, 0xa0, 0x7b, 0xfc, 0xd3, 0x16, 0x92,
	0x47, 0x95, 0xc8, 0x33, 0xd2, 0x9f, 0x23, 0xf3, 0x3f, 0xfd, 0xc5, 0x6a, 0xc7, 0x4f, 0xe3, 0xd6,
	0x19, 0x34, 0x4e, 0x97, 0xe1, 0x23, 0x18, 0xdd, 0x71, 0x91, 0x3c, 0x55, 0x64, 0xa8, 0xda, 0x9f,
	0x84, 0x8f, 0x61, 0x72, 0x9d, 0x72, 0x26, 0x6f, 0x52, 0x96, 0x90, 0x91, 0xba, 0xaf, 0x05, 0xf8,
	0x0c, 0x66, 0xcd, 0x45, 0x94, 0xbf, 0xbd, 0x0b, 0xc9, 0x63, 0x32, 0x56, 0xca, 0x1f, 0x8a, 0x75,
	0x40, 0x5b, 0xa2, 0xa9, 0x87, 0xd1, 0xb6, 0x4e, 0x3b, 0x32, 0x69, 0xd2, 0xee, 0xfc, 0x0a, 0xa0,
	0xfd, 0x15, 0xd6, 0x60, 0xe0, 0xda, 0x6b, 0xc7, 0xf8, 0x87, 0x27, 0x30, 0xbc, 0xf7, 0x1f, 0x1c,
	0xdb, 0x40, 0x78, 0x0a, 0x63, 0xba, 0xf1, 0x3c, 0xd7, 0xbb, 0x35, 0x7a, 0x58, 0x07, 0x2d, 0x74,
	0xd6, 0x4e, 0xe0, 0xd3, 0xd0, 0xe8, 0xaf, 0x0e, 0x57, 0x07, 0xdd, 0x41, 0x83, 0x7a, 0xe6, 0xc7,
	0x91, 0x5a, 0xfb, 0xf2, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x0d, 0xe4, 0xce, 0x22, 0x99, 0x01, 0x00,
	0x00,
}
